alias: Enregistrer consomation de la journée
description: ''
trigger:
  - platform: time
    at: '00:00'
condition: []
action:
  - service: counter.configure
    data:
      value: '{{ states("sensor.linky_hc") | int}}'
    target:
      entity_id: counter.hc_end_journey
  - service: counter.configure
    data:
      value: '{{ states("sensor.linky_hp") | int}}'
    target:
      entity_id: counter.hp_end_journey
  - service: counter.configure
    data: {}
    target:
      entity_id: counter.endhc
mode: single
