esphome:
  name: esp_linky
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Wifi"
  password: "password"

captive_portal:
logger:
  #level: VERY_VERBOSE
api:
ota:

uart:
  id: uart_bus
  rx_pin: D7
  tx_pin: D6
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

teleinfo:
  id: myteleinfo
  update_interval: 60s
  historical_mode: true


sensor:
  - platform: teleinfo
    tag_name: "HCHC"
    name: "Linky HC"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "HCHP"
    name: "Linky HP"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo
  
  - platform: teleinfo
    tag_name: "PAPP"
    name: "Linky Consommation"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "IINST"
    name: "Linky Intensité"
    unit_of_measurement: "A"
    icon: mdi:flash
    teleinfo_id: myteleinfo
